### ISSUE TITLE
大哥这是咋整的？

### ISSUE THREAD

**Issue by dagedan** [GeSnowBoy/vue-gecode#2]
WebSocket connection to 'wss://live.github.com/_sockets/VjI6MTgyOTMyOTUzOmMyMGIwZGM0OGQ5YWQxZTRhYWQ4…M2I0YTM4MjgxYTZlODNkODc3NTMwZjQ=--694216f384a68a025e3335420d5592a70c0e7c51' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

**Comment by GeSnowBoy** [comment]
你这是什么东西  我刚发布的你怎么找到的呢?
